name: Create Releases
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install required packagestg
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full zip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pyglossary
      	run: |
      		python -m pip install --upgrade pip
      		pip install pyglossary lxml beautifulsoup4
      - name: Extract .7z files
        run: |
          for file in *.7z.001*; do
            if [ -f "$file" ]; then
              7z x "$file" -aoa
            fi
          done
      - name: Run pyglossary
      	run: |
      		pyglossary ./HanYuDaCiDian-2.0-html.txt ./HanYuDaCiDian-2.0-stardict-html --read-format=Tabfile --write-format=Stardict --name=HanYuDaCiDian
      		pyglossary ./HanYuDaCiDian-2.0-html.txt ./HanYuDaCiDian-2.0-stardict-plaintext --read-format=Tabfile --write-format=Stardict --name=HanYuDaCiDian --write-options="sametypesequence=m"
      		pyglossary ./HanYuDaCiDian-2.0-html.txt ./HanYuDaCiDian-2.0-yomitan.zip --read-format=Tabfile --write-format=Yomichan --name=HanYuDaCiDian
      		python html2ansi.py ./HanYuDaCiDian-2.0-html.txt ./HanYuDaCiDian-2.0-html2ansi.txt
      		pyglossary ./HanYuDaCiDian-2.0-html2ansi.txt ./HanYuDaCiDian-2.0-stardict-html2ansi --read-format=Tabfile --write-format=Stardict --name=HanYuDaCiDian
      - name: Create zip and tar.gz files
        run: |
          for dir in HanYuDaCiDian-2.0-stardict-html HanYuDaCiDian-2.0-stardict-html2ansi HanYuDaCiDian-2.0-stardict-plaintext; do
            if [ -d "$dir" ]; then
              zip -r "${dir}.zip" "$dir"
            else
              echo "Directory $dir does not exist, skipping..."
            fi
          done
      - name: Pre-release
        run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref }}
          files: |
            *.zip
