name: Create Releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
      release_name:
        description: 'Release name'
        required: true
        type: string
        default: ''

permissions:
  contents: write

env:
  VERSION: ${{ github.event.inputs.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install pyglossary and dependencies
        run: pip install pyglossary lxml beautifulsoup4 python-idzip tqdm pyicu

      - name: (HanYuDaCiDian) Download the tabfile
        env:
          VERSION: ${{ env.VERSION }}
        run: wget https://github.com/scillidan/file_hanyudacidian/releases/download/${VERSION}/_hanyudacidian-${VERSION}-formatted.txt

      - name: Convert with pyglossary and python scripts
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          filename: hanyudacidian-${VERSION}
          dictname: HanYuDaCiDian

          # stardict
          pyglossary ./_${fliename}-formatted.txt ./${fliename}-stardict --read-format=Tabfile --write-format=Stardict --name=${VERSION}

          # tabfile-formatted-html2ansi
          python html2ansi.py ./_${fliename}-formatted.txt ./_${fliename}-formatted-html2ansi.txt

          # sdcv
          pyglossary ./_${fliename}-formatted-html2ansi.txt ./${fliename}-sdcv --read-format=Tabfile --write-format=Stardict --name=${VERSION}

          # pyglossary ./_${fliename}-formatted-html2ansi.txt ./${fliename}-sdcv-mergesyns --read-format=Tabfile --write-format=StardictMergeSyns --name=${VERSION}

          # dictd
          # Not support searching CJK words at present, check https://fossies.org/linux/dictd/TODO.
          # pyglossary ./_${fliename}-formatted-html2ansi.txt ./${fliename}-dictd --read-format=Tabfile --write-format=DictOrg --write-options="dictzip=true" --name=${VERSION}

          # yomichan
          pyglossary ./_${fliename}-formatted.txt ./${fliename}-yomichan.zip --read-format=Tabfile --write-format=Yomichan --name=${VERSION}

          # aard2
          pyglossary ./_${fliename}-formatted.txt ./${fliename}-aard2.slob --read-format=Tabfile --write-format=Aard2Slob --name=${VERSION}

      - name: ZIP stardict
        run: |
          for base in *.ifo; do
            prefix="${base%.ifo}"
            zip -j "${prefix}.zip" "$prefix".{ifo,dict,idx,syn} 2>/dev/null
          done

      # - name: ZIP dictd
      #   run: |
      #     for base in *.index; do
      #       prefix="${base%.index}"
      #       zip -j "${prefix}.zip" "$prefix".{index,dict.dz} 2>/dev/null
      #     done

      - name: Generate SHA256 checksums
        run: |
          for file in *.{txt,zip,slob}; do
            sha256sum "$file" > "$file.sha256"
          done

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name || github.event.inputs.tag_name }}
          files: |
            *.{txt,zip,slob}
